#!/usr/bin/env bash
# Transfer file to server

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <file_path> <server_ip> <username> <ssh_private_key_path>"
    exit 1
fi

SOURCE_FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
PRIVATE_KEY="$4"

scp -i "$PRIVATE_KEY" "$SOURCE_FILE" "$USERNAME@$SERVER_IP:~"
