#!/usr/bin/env bash
# Steps taken to install nginx

sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx start
