#!/usr/bin/env bash
# Steps taken to install nginx

apt update -y
apt install nginx -y
echo "Hello World!" | sudo tree /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx start
