#!/usr/bin/env bash
# Steps taken to install nginx

apt update -y
apt install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i 's/^listen [0-9]*;/listen 80;/' /etc/nginx/sites-enabled/default

nginx
