#!/usr/bin/env bash
# script for redirecting while visiting /redirect_me

sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i '/^.*location \/ {/,/^.*}/ a\
\    location /redirect_me {\n\        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\    }
' /etc/nginx/sites-available/default

sudo service nginx restart
