#!/usr/bin/env bash
# script for redirecting while visiting /redirect_me

# apt update -y
# apt install nginx -y
# echo "Hello World!" | sudo tree /var/www/html/index.html

sed -i '/^.*location \/ {/,/^.*}/ a\
\    location /redirect_me {\n\        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\    }
' /etc/nginx/sites-available/default

pkill -9 nginx
nginx -s reload
